config/routes.rb
Rails.application.routes.draw do
  resources :travellers
  mount Monologue::Engine, at: '/blog'
  resources :contacts
  root 'welcome#index'
  get '/faq', to: 'welcome#faq'
  get '/about_us', to: 'welcome#about_us'
  get '/pricing', to: 'welcome#pricing'
  get '/how_it_works', to: 'welcome#how_it_works'
  get '/faq', to: 'welcome#faq'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email)
    end
end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
  before_action :set_traveller, only: [:show, :edit, :update, :destroy]

  # GET /travellers
  # GET /travellers.json
  def index
    @travellers = Traveller.all
  end

  # GET /travellers/1
  # GET /travellers/1.json
  def show
  end

  # GET /travellers/new
  def new
    @traveller = Traveller.new
  end

  # GET /travellers/1/edit
  def edit
  end

  # POST /travellers
  # POST /travellers.json
  def create
    @traveller = Traveller.new(traveller_params)

    respond_to do |format|
      if @traveller.save
        format.html { redirect_to root_path, notice: 'Traveller was successfully created.' }
        format.json { render :show, status: :created, location: @traveller }
      else
        format.html { render :new }
        format.json { render json: @traveller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travellers/1
  # PATCH/PUT /travellers/1.json
  def update
    respond_to do |format|
      if @traveller.update(traveller_params)
        format.html { redirect_to @traveller, notice: 'Traveller was successfully updated.' }
        format.json { render :show, status: :ok, location: @traveller }
      else
        format.html { render :edit }
        format.json { render json: @traveller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travellers/1
  # DELETE /travellers/1.json
  def destroy
    @traveller.destroy
    respond_to do |format|
      format.html { redirect_to travellers_url, notice: 'Traveller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traveller
      @traveller = Traveller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traveller_params
      params.require(:traveller).permit(:first_name, :last_name_string, :email, :phone, :flying_from, :flying_to, :departure_date, :return_date, :flexible, :request_type, :mileage_program, :miles_balance, :comments)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def how_it_works
  end
  def pricing
  end
  def faq
  end
  def about_us
  end
  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/views/layouts/monologue/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monologue</title>
  <%= stylesheet_link_tag    "monologue/admin/application" %>
  <%= javascript_include_tag "monologue/admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <% if monologue_current_user %>
    <%= render "layouts/monologue/admin/nav_bar" %>
  <% end %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: (name == 'notice' ? "alert alert-info" : "alert alert-error") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/monologue/admin/_nav_bar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container" data-monologue="nav-bar">
      <%= link_to "Admin", admin_path, class: "brand" %>
      <ul class="nav pull-left" data-monologue="nav-bar-left">
        <%= activable_li_tag_with_link t("New Article"), new_admin_post_path %>
        <%= activable_li_tag_with_link t("List of Articles"), admin_posts_path, admin_path %>
        <%= activable_li_tag_with_link t("Comments"), admin_comments_path %>
      </ul>

      <ul class="nav pull-right" data-monologue="nav-bar-right">
        <%= activable_li_tag_with_link t(".users"), admin_users_path %>
        <li id="fat-menu" class="dropdown">
          <a href="#" id="settings" data-toggle="dropdown"><%= t(".settings") %> <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="settings">
            <li><%= link_to t(".edit_user_info"), edit_admin_user_path(monologue_current_user)%></li>
          </ul>
        </li>
        <li><%= link_to t(".log_out"), admin_logout_path %></li>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/monologue/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Miles 4 Dummies" %></title>
    <meta name="description" content="Miles 4 Dummies">
    <meta name="name" content="Miles 4 Dummies">
    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
    <%= favicon_link_tag %>
    <link href="/assets/bootstrap.min.css" media="all" rel="stylesheet" />
    <link href="/assets/bootstrap-theme.min.css" media="all" rel="stylesheet" />
    <link href="/assets/custom.scss" media="all" rel="stylesheet" />
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/jquery.min.js"></script>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render partial: "layouts/navigation" %>
      <%= yield %> 
    <%= render partial: "layouts/footer" %>     
  </body>
</html>

app/views/layouts/monologue/application/_disqus.html.erb
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '<%= Monologue::Config.disqus_shortname%>'; // required: replace example with your forum shortname

  <% if Rails.env.development?  %>
  var disqus_developer = 1; // developer mode is on
  <% end %>


  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());
</script>

app/views/layouts/monologue/application/_disqus_embed.html.erb
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '<%= Monologue::Config.disqus_shortname%>'; // required: replace example with your forum shortname

  <% if Rails.env.development?  %>
  var disqus_developer = 1; // developer mode is on
  <% end %>

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

app/views/layouts/monologue/application/_meta_description.html.erb
<meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : Monologue::Config.meta_description  %>" />

app/views/layouts/monologue/application/_sidebar.html.erb
<% if Monologue::Config.sidebar %>
<aside class="sidebar four columns">
   <% Monologue::Config.sidebar.each do |ext| %>
     <%= render partial: "monologue/sidebar/#{ext}" %>
   <% end %>
</aside>
<% end %>

app/views/welcome/about_us.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron" id="about-header">
       <div class="container">
          <h1>About our company</h1>
       </div>
    </div>
  </div>
  <div class="row" id="about">
    <div class="col-lg-6">
      <p>Our CEO, Marcela Alvarez Calderon, created Miles4Dummies after spending years travelling, researching and analyzing Mileage programs, their upsides and their tricks. Using the right mix of technology and savoir-faire she has saved thousands of dollars, travelled the world and advised numerous travellers in the art of 'travel hacking'. She created Miles4Dummies to scout the best deals, advise smart adventurers, find win-win Mile scenarios and give clients a "one stop shop" for all their Miles needs.</p><br>
      <p>Marcela decided to turn her hobby and passion into a full time consultancy after organizing everything from pro bono expeditions in the Amazonian jungles to high luxury ski vacations in the Alps. She travelled to every corner of the world, from Siberia to Ushuaia, amassing a diverse network of partners and alliances allowing her to find the best deals at the blink of an eye.</p><br>
      <p>With a career ranging from Kellog's Foundation ambassador in Central America to consulting for AVINA on water preservation around the globe, she has been racking miles since before she can even remember. Get in touch with us and let Marcela do her magic.</p>
    </div>
    <div class="col-lg-6">
      <%= image_tag('marcela.png', :class => "img-responsive") %>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row" id="call-to-action">
    <div class="col-lg-12">
      <h1 class="text-center">Discover the potential behind your travel Miles.</h1>
      <%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/welcome/faq.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron" id="faq-header">
       <div class="container">
          <h1>Frequently Asked Questions</h1>
       </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p id="question">1. Why choose Miles4Dummies?</p>
      <p id="answer">The quick answer...because we make your travelling feel like a walk in the park. Booking free seats with frequent flyer miles is more difficult than ever as airlines have further complicated the rules and fewer seats are available. Hotels are popping up at a never before seen rate, all with different programs and different rewards. Miles4Dummies has the network, the experience, the knowledge and the resources to advise you in the art of travel hacking.</p>
      <p id="question">2. Are you a travel agency?</p>
      <p id="answer">We are not. But that doesn't mean we can't book your around the world tickets and get you the hotel room of your deals. We specialise in travel miles consulting but we are fully capable of taking care of all your travel needs.</p>
      <p id="question">3. What services do you offer?</p>
      <p id="answer">If you have the Miles and the desire to explore we have the magic lamp to grant your wishes. We will get you award tickets, upgrade your travel accomodations, optimise your airfare, arrange the ideal redemption for your Miles, book your entire vacation, teach you how to travel the world for free and more.</p>
      <p id="question">4. Is it better to redeem or to sell my Miles?</p>
      <p id="answer">In order to know that we would have to study your personal needs and based on that we could advise you on what would be the best strategy regarding your Miles. By filling out our "Request a Quote" form we will get in touch with you and proceed to find out what is the best scenario for you.</p>
      <p id="question">5. What is the best plan for me?</p>
      <p id="answer">It all depends on your needs and desires. If you want to book your next trip and learn how to earn more Miles with just a few changes in your habits and your loyalty programs, then the Adventurer is the best option for you. But if you want to conquer the Miles world, redeem like a champion and learn how to earn thousands of miles without even breaking a sweat, then the Globetrotter is the plan for you. We have a plan suited for every traveller.</p>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row" id="call-to-action">
    <div class="col-lg-12">
      <h1 class="text-center">Discover the potential behind your travel Miles.</h1>
      <p><%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>

app/views/welcome/how_it_works.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron" id="sell-header">
       <div class="container">
          <h1>Using your Miles should be easy</h1>
       </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p>If you are here it's because you have already taken care of the hard part...accumulating those precious Miles. It doesn't matter if it was when you were working at that multinational that made you travel every other week to the other side of the Atlantic or if it was the infinite weekend trips you took to see your loved one when you were doing your Masters. The hard part is done. Now it's time for you to relax and let us take care of everything. All it takes is three simple steps for us to get all the information we need and for you to put your next adventure on autopilot.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <h2>1. Choose one of our Plans</h2>
      <p>We have studied countless scenarios, budgets and personalities to come up with three pricing plans that will blow your mind away. Whether you are a solo traveller or a full family going on a luxury getaway, we have you covered.</p><br><br>
      <p>Take a close look at all the options available in each plan and check to see which ones suit your travelling needs. Maybe you only want some quick advise and some help booking that surf trip to Hawaii. Or maybe it gets more complex than that and you want to learn how to master the art of travel hacking. Whatever your decision is, let us know and we will make it a reality.</p>
    </div>
    <div class="col-lg-6">
      <%= image_tag('pricing-how.png', :class => "featurette-image img-circle img-responsive pull-right", :style => "border: 2px solid #c485cd;") %>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row">
    <div class="col-lg-6">
      <%= image_tag('form-how.png', :class => "featurette-image img-circle img-responsive pull-right", :style => "border: 2px solid #c485cd;") %>
    </div>
    <div class="col-lg-6">
      <h2>2. Request a Quote from us</h2>
      <p>It takes less than 5 minutes and it can save you a lifetime of hassle and complication. Like we said, you have already taken care of the hard part of the journey. You have those Miles in your pocket. Now we need to know a few details to make sure that everything you desire is well addressed and taken care of.</p>
      <p>Fill out our 'Request a Quote' form by hitting any of the Get Started links scattered throughout the site. In the form you will be asked for a few personal details, mainly to get in touch with you, and also some of your preferences regarding Mileage programs, destinations and specific instructions regarding your trip.</p>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row">
    <div class="col-lg-6">
      <h2>3. We contact you</h2>
      <p>With all the information you gave us we begin to turn our engines. We consult our deals platform to find out the latest offers that match your details. Using our partner network and insider knowledge we begin to build the ideal scenario for your travel needs.</p>
      <p>Once we have put together a dossier with all the necessary points, we contact you by email to arrange a one-on-one conversation by phone where, according to the plan you have chosen, we give you the A to Z on how to use your Miles to open the gates to the world.</p>
    </div>
    <div class="col-lg-6">
      <%= image_tag('travel-how.png', :class => "featurette-image img-circle img-responsive pull-right", :style => "border: 2px solid #c485cd;") %>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row" id="homepage-partners">
    <div class="row">
      <div class="col-lg-3 text-center">
        <%= image_tag('delta.jpg', :class => "img-responsive", :style => "padding-top:3em;") %>
      </div>
      <div class="col-lg-3 text-center">
        <%= image_tag('copa.png', :class => "img-responsive", :style => "padding-top:3em;") %>
      </div>
      <div class="col-lg-3 text-center">
        <%= image_tag('klm.png', :class => "img-responsive", :style => "padding-bottom:2em;") %>
      </div>
      <div class="col-lg-3 text-center">
        <%= image_tag('american.png', :class => "img-responsive", :style => "padding-bottom:2em;") %>
      </div>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row" id="call-to-action">
    <div class="col-lg-12">
      <h1 class="text-center">Discover the potential behind your travel Miles.</h1>
      <p><%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron" id="homepage-header">
       <div class="container">
          <h1>Start enjoying your travel Miles</h1>
          <h2>Get advise from the world's top travel miles consultant</h2>
          <p><%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg", form_class: "header-form-button" %></p>
       </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-4 text-center" id="homepage-features">
      <i class="fa fa-info-circle fa-4x"></i>
      <h2>Learn about Miles</h2>
      <p>Join us. Read articles, watch videos, get the latest offers and learn everything about your Miles.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-features">
      <i class="fa fa-plane fa-4x"></i>
      <h2>Earn more Miles</h2>
      <p>Optimise your travel and spending habits. Use the best loyalty programs. Travel smartly.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-features">
      <i class="fa fa-dollar fa-4x"></i>
      <h2>Redeem your Miles</h2>
      <p>Find the latest offers and rewards that match your Miles, your needs and your desires.</p>
    </div>
  </div>

  <div class="row" id="homepage-services">
    <div class="col-lg-12 text-center">
      <h1>What is Miles4Dummies?</h1>
      <p id="homepage-services-bio">Our CEO, Marcela Alvarez Calderon, created Miles4Dummies after spending years travelling, researching and analyzing Mileage programs, their upsides and their tricks. Using the right mix of technology and savoir-faire she has saved thousands of dollars, travelled the world and advised numerous travellers in the art of 'travel hacking'. She created Miles4Dummies to scout the best deals, advise smart adventurers, find win-win Mile scenarios and give clients a "one stop shop" for all their Miles needs. Here are some of our services.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-phone fa-4x"></i>
      <h2>Premium Consulting</h2>
      <p>Our #1 service. We get you on the phone, jot down the details and become your personal Miles consultant.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-trophy fa-4x"></i>
      <h2>Best of the Month</h2>
      <p>Find the latest offers and rewards that match to your Miles, your needs and your desires.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-calculator fa-4x"></i>
      <h2>Miles Calculator</h2>
      <p>Use our mile exchange calculator to get a clear idea if it's better for you to sell all those accumulated miles. </p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-globe fa-4x"></i>
      <h2>Smart Travel Network</h2>
      <p>Join us. Read articles, watch videos, get the latest offers and learn everything about your Miles.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-group fa-4x"></i>
      <h2>Certified Partners</h2>
      <p>Get access to all our travel partners and their latest offers all tailored to your every need.</p>
    </div>
    <div class="col-lg-4 text-center" id="homepage-services-block">
      <i class="fa fa-flash fa-4x"></i>
      <h2>Flash Offers and Deals</h2>
      <p>We don't want you to miss out on anything. Join us and you will get instant alerts on the hottest deals.</p>
    </div>
  </div>
<!--   <div class="row" id="homepage-testimonials">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Our clients love us</h1>
      </div>
      <div class="col-md-12" data-wow-delay="5s">
        <div class="carousel slide" data-ride="carousel" id="quote-carousel">

          <div class="carousel-inner text-center">

            <div class="item active">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p><i class="fa fa-quote-left"></i> "We were planning our honeymoon and had more than 200,000 miles accumulated between us. Marcela helped us plan the trip a lifetime. " <i class="fa fa-quote-right"></i></p>
                    <p style="font-weight:900; margin-top:1em;">John Mendez, CEO Manufacturing & Co.</p>
                  </div>
                </div>
              </blockquote>
            </div>
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p><i class="fa fa-quote-left"></i> "While working at a multinational I racked up more than 1.5 million miles. After deciding to cash in I got Miles4Dummies on the phone to start finding the ideal price." <i class="fa fa-quote-right"></i></p>
                    <p style="font-weight:900; margin-top:1em;">Pedro Heilbron, President COPA Airlines</p>
                  </div>
                </div>
              </blockquote>
            </div>
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p><i class="fa fa-quote-left"></i> "I had been wanting to go to NYC and stay at the Plaza Hotel (just like Home Alone). Marcela made it happen with just a few calls here and a few miles there." <i class="fa fa-quote-right"></i></p>
                    <p style="font-weight:900; margin-top:1em;">Andrea Sanchez, Designer</p>
                  </div>
                </div>
              </blockquote>
            </div>
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p><i class="fa fa-quote-left"></i> "It's hard to imagine what you can do with a solid mileage program and a few experts advising you. Round the world trip in 13 months. Thank you Miles4Dummies." <i class="fa fa-quote-right"></i></p>
                    <p style="font-weight:900; margin-top:1em;">Jack Andrews, Lawyer</p>
                  </div>
                </div>
              </blockquote>
            </div>
          </div>

          <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
          <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
        </div>
      </div>
    </div>

  </div> -->
  <div class="row" id="call-to-action">
    <div class="col-lg-12">
      <h1 class="text-center">Discover the potential behind your travel Miles.</h1>
      <p><%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>
<a name="testimonials"></a>

app/views/welcome/pricing.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron" id="redeem-header">
       <div class="container">
          <h1>Pricing for every type of customer</h1>
       </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p>We created this company because we valued smart and simple travelling. And we want to share that with you. In order to cater to a very diverse audience we created three plans that encapsulate the essence of travel hacking from a basic degree to a full on mastery of the domain. While some of you might just want to start earning miles more efficiently or book your next trip with all those hard earned miles, others may want to learn the steps more methodically in order to apply that knowledge in their future travel plans. Whatever your level of expertise or your learning preference, we will create a customized plan just for you.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 text-center" id="pricing-box">
      <h2>The Adventurer</h2>
      <hr>
      <p>Our starter package. We will analyze your travel habits and your favorite spending patterns to get you earning thousands of Miles at the blink of an eye. You will learn how to optimise your Mile accumulation so you can start planning your next trip.</p>
      <hr>
      <h1>$350</h1>
      <hr>
      <p>* One session (1 hour total) of one-on-one consulting</p>
      <p>* Credit card recommendations</p>
      <p>* Airline and hotel loyalty programs</p>
      <p>* Strategic spending plan</p>
      <p>* Detailed Mile accumulation brief</p>
    </div>
    <div class="col-lg-4 text-center" id="pricing-box">
      <h2>The Traveller</h2>
      <hr>
      <p>Our most popular package. Not only will we analyze your habits and teach you how to earn more Miles, but we will show you how to redeem your Miles in the most efficient way possible. The result will be more travelling with less Miles spent.</p>
      <hr>
      <h1>$600</h1>
      <hr>
      <p>* Two sessions (3 hours total) of one-on-one consulting</p>
      <p>* Credit card recommendations</p>
      <p>* Airline and hotel loyalty programs</p>
      <p>* Strategic spending plan</p>
      <p>* Detailed Mile accumulation brief</p>
      <p>* Customized Mile redemption strategy</p>
    </div>
    <div class="col-lg-4 text-center" id="pricing-box">
      <h2>The Globetrotter</h2>
      <hr>
      <p>Our all star package. For those who want to go from novice to travel hacker, this is your chance. We will teach you everything we know, from earning to redeeming to selling your Miles, so that you can become autonomous and plan all your travels.</p>
      <hr>
      <h1>$950</h1>
      <hr>
      <p>* Four sessions (6 hours total) of one-on-one consulting</p>
      <p>* Credit card recommendations</p>
      <p>* Airline and hotel loyalty programs</p>
      <p>* Strategic spending plan</p>
      <p>* Detailed Mile accumulation brief</p>
      <p>* Customized Mile redemption strategy</p>
      <p>* Travel hacking ebook</p>
    </div>
  </div>
  <hr class="featurette-divider">
  <div class="row" id="call-to-action">
    <div class="col-lg-12">
      <h1 class="text-center">Discover the potential behind your travel Miles.</h1>
      <p><%= button_to "Get started", new_traveller_path, method: :get, class: "btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>